AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - beta
      - gamma
      - prod
    Default: beta
    Description: Stage that can be added to resource names

Resources:
  brwyattapi:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: api.brwyatt.net
      Description: Code for api.brwyatt.net
      ContentUri: build/
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Retain

  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: time.handler
      CodeUri: lambda/time.py
      Runtime: python3.7
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /time
            Method: GET
      Layers:
        - !Ref brwyattapi

Outputs:
  ApiUrl:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: !Sub 'ApiUrl-${Stage}'
