AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.7
    Layers:
      - !Ref BrwyattLayer

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - Beta
      - Gamma
      - Prod
    Default: Beta
    Description: Stage that can be added to resource names
  ApiDomain:
    Type: String
    Default: 'api.brwyatt.net'
    Description: API domain name
  WebDomain:
    Type: String
    Default: 'brwyatt.net'
    Description: Web UI domain name

Resources:
  BrwyattWeb:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'Brwyatt-Web-${Stage}'
      StageName: !Ref Stage
      Variables:
        Stage: !Ref Stage

  WebMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: BrwyattWebStage
    Properties:
      BasePath: ''
      DomainName: !Ref WebDomain
      RestApiId: !Ref BrwyattWeb
      Stage: !Ref Stage

  BrwyattApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'Brwyatt-API-${Stage}'
      StageName: !Ref Stage
      Variables:
        Stage: !Ref Stage

  ApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: BrwyattApiStage
    Properties:
      BasePath: ''
      DomainName: !Ref ApiDomain
      RestApiId: !Ref BrwyattApi
      Stage: !Ref Stage

  WebApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: BrwyattApiStage
    Properties:
      BasePath: 'api'
      DomainName: !Ref WebDomain
      RestApiId: !Ref BrwyattApi
      Stage: !Ref Stage

  BrwyattLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'Brwyatt-${Stage}'
      Description: Code for brwyatt.net
      ContentUri: build/
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - python3.7

  ApiTime:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_time.handler
      CodeUri: lambda/get_time.py
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            RestApiId: !Ref BrwyattApi
            Path: /time
            Method: GET

  ApiTestLayer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_test_layer.handler
      CodeUri: lambda/get_test_layer.py
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            RestApiId: !Ref BrwyattApi
            Path: /test_layer
            Method: GET

  WebHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello_world.handler
      CodeUri: lambda/hello_world.py
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            RestApiId: !Ref BrwyattWeb
            Path: /
            Method: GET

Outputs:
  ApiUrl:
    Description: URL for application API
    Value: !Sub 'https://${ApiDomain}/'
    Export:
      Name: !Sub 'ApiUrl-${Stage}'

# vim: ts=2 sts=2 sw=2 expandtab
