AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ServiceName:
    Type: String
    Default: BrwyattWeb
    Description: Name of the service - Used in all resources
  BaseDomain:
    Type: String
    Default: brwyatt.net
    Description: Base Domain name for application URLs
  GitHubUser:
    Type: String
    Description: GitHub UserName. This username must have access to the GitHubToken
    Default: brwyatt
  GitHubRepoName:
    Type: String
    Description: The GitHub repo name
    Default: brwyatt.net
  GitHubRepoBranch:
    Type: String
    Description: The GitHub repo branch code pipelines should watch for changes on
    Default: master
  GitHubToken:
    NoEcho: true
    Type: String
    Description: >-
      Secret. OAuthToken with access to Repo. Long string of characters and
      digits. Go to https://github.com/settings/tokens
Resources:
  BuildArtifactsBucket:
    Type: 'AWS::S3::Bucket'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 55c6df7a-f27a-49e9-800c-8fb2f85e04ab
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub >-
                    arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ServiceName}_build
                  - !Sub >-
                    arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ServiceName}_build:*
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
              - Effect: Allow
                Resource:
                  - !Sub 'arn:aws:s3:::${BuildArtifactsBucket}/*'
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:PutObject'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8ac9f794-ebc0-4cf6-b4c4-431fcf9b64c1
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${ServiceName}_build'
      Description: !Sub 'Build project for the ${ServiceName} service'
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: ARM_LAMBDA_CONTAINER
        ComputeType: BUILD_LAMBDA_1GB
        Image: 'aws/codebuild/amazonlinux-aarch64-lambda-standard:python3.12'
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !Ref BuildArtifactsBucket
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: CODEPIPELINE
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ab1dc439-a120-4b5e-b4a6-f185a350c61c
  CFNPipelinePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: CloudFormation Pipeline Execution Policy
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action:
            - 'cloudformation:CreateStack'
            - 'cloudformation:DescribeStacks'
            - 'cloudformation:DeleteStack'
            - 'cloudformation:UpdateStack'
            - 'cloudformation:CreateChangeSet'
            - 'cloudformation:ExecuteChangeSet'
            - 'cloudformation:DeleteChangeSet'
            - 'cloudformation:DescribeChangeSet'
            - 'cloudformation:SetStackPolicy'
            - 'cloudformation:SetStackPolicy'
            - 'cloudformation:ValidateTemplate'
            - 'codebuild:StartBuild'
            - 'codebuild:BatchGetBuilds'
          Resource: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e89a5cfb-a421-4de1-9c09-7e95dd1be69c
  CloudFormationExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action:
            - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service:
              - cloudformation.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d56dfbef-19b8-4995-8fd9-55950aa8444a
  PipelineExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSCodeCommitFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - !Ref CFNPipelinePolicy
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'iam:PassRole'
                  - 'lambda:InvokeFunction'
                  - 'lambda:ListFunctions'
                  - 'lambda:InvokeAsyc'
                Effect: Allow
                Resource: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c97c4d35-3ecb-4bef-9a1a-f406d4d3ec0f
  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Location: !Ref BuildArtifactsBucket
        Type: S3
      Name: !Sub '${ServiceName}_pipeline'
      RoleArn: !GetAtt PipelineExecutionRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubRepo
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubRepoBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceZip
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceZip
              OutputArtifacts:
                - Name: BuiltZip
        - Name: Beta
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: !Sub '${ServiceName}-Beta'
                ChangeSetName: !Sub '${ServiceName}-ChangeSet-Beta'
                TemplatePath: 'BuiltZip::app-output_sam.yaml'
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: !Sub |
                  {
                    "Stage": "Beta",
                    "WebDomain": "beta.${BaseDomain}",
                    "ApiDomain": "api.beta.${BaseDomain}"
                  }
              InputArtifacts:
                - Name: BuiltZip
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: !Sub '${ServiceName}-Beta'
                ChangeSetName: !Sub '${ServiceName}-ChangeSet-Beta'
              OutputArtifacts:
                - Name: !Sub '${ServiceName}BetaChangeSet'
              RunOrder: 2
        - Name: Gamma
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: !Sub '${ServiceName}-Gamma'
                ChangeSetName: !Sub '${ServiceName}-ChangeSet-Gamma'
                TemplatePath: 'BuiltZip::app-output_sam.yaml'
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: !Sub |
                  {
                    "Stage": "Gamma",
                    "WebDomain": "gamma.${BaseDomain}",
                    "ApiDomain": "api.gamma.${BaseDomain}"
                  }
              InputArtifacts:
                - Name: BuiltZip
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: !Sub '${ServiceName}-Gamma'
                ChangeSetName: !Sub '${ServiceName}-ChangeSet-Gamma'
              OutputArtifacts:
                - Name: !Sub '${ServiceName}GammaChangeSet'
              RunOrder: 2
        - Name: Prod
          Actions:
            - Name: DeploymentApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              RunOrder: 1
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: !Sub '${ServiceName}-Prod'
                ChangeSetName: !Sub '${ServiceName}-ChangeSet-Prod'
                TemplatePath: 'BuiltZip::app-output_sam.yaml'
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: !Sub |
                  {
                    "Stage": "Prod",
                    "WebDomain": "${BaseDomain}",
                    "ApiDomain": "api.${BaseDomain}"
                  }
              InputArtifacts:
                - Name: BuiltZip
              RunOrder: 2
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: !Sub '${ServiceName}-Prod'
                ChangeSetName: !Sub '${ServiceName}-ChangeSet-Prod'
              OutputArtifacts:
                - Name: !Sub '${ServiceName}ProdChangeSet'
              RunOrder: 3
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 46ddb31c-ae67-48c6-88e8-f9cf2cc4d1e3
Metadata:
  'AWS::CloudFormation::Designer':
    d56dfbef-19b8-4995-8fd9-55950aa8444a:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    e89a5cfb-a421-4de1-9c09-7e95dd1be69c:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
    c97c4d35-3ecb-4bef-9a1a-f406d4d3ec0f:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 210
      z: 1
      embeds: []
    8ac9f794-ebc0-4cf6-b4c4-431fcf9b64c1:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 210
      z: 1
      embeds: []
    55c6df7a-f27a-49e9-800c-8fb2f85e04ab:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 90
      z: 1
      embeds: []
    ab1dc439-a120-4b5e-b4a6-f185a350c61c:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 210
      z: 1
      embeds: []
    46ddb31c-ae67-48c6-88e8-f9cf2cc4d1e3:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 330
      z: 1
      embeds: []
