---
'css': '/css/{resource+}'
'js': '/js/{resource+}'
'ads': '/ads.txt'
'favicon': '/favicon.ico'
'keybase': '/keybase.txt'
'robots': '/robots.txt'
'openpgpkey': '/.well-known/openpgpkey/{pgpdata+}'
'mtasts': '/.well-known/mta-sts.txt'

# vim: ts=2 sts=2 sw=2 expandtab
